global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'crud'
    static_configs:
      - targets: ['crud:5000']

  - job_name: 'openfoodfacts'
    static_configs:
      - targets: ['openfoodfacts:5000']

  - job_name: 'business_logic'
    static_configs:
      - targets: ['business_logic:5000']