name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - miruna
      - rares
      - miruna_etapa_finala
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install docker compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build project
        run: |
          docker-compose build

      - name: Deploy project
        run: |
          docker-compose up -d
